// Función para construir rutas de imágenes
function img(categoria, carpeta) {
  return `/images/comercializadora/${categoria}/${carpeta}/1.jpg`;
}

// Toggle para activar/desactivar etiquetas de descuento en las tarjetas
// Cambia a `true` cuando quieras volver a mostrarlas.
const DESCUENTOS_ACTIVOS = false;

// Base de datos de productos centralizada
const productos = [
  // ================= LAVADORAS =================
  {
    id: 1,
    nombre: "Lavadora 11 kg Hisense Semiautomática",
    categoria: "Lavadoras",
    imagen: img("lavadoras", "hisense-11-kg"),
    contado: 3599,
    total: 4299,
    enganche: 300,
    financiado: 3999,
    semanas: 16,
    pago: 250,
    destacado: false,
  },
  {
    id: 2,
    nombre: "Lavadora 13 kg Mirage Semiautomática",
    categoria: "Lavadoras",
    imagen: img("lavadoras", "mirage-13-kg"),
    contado: 4299,
    total: 4999,
    enganche: 300,
    financiado: 4699,
    semanas: 18,
    pago: 262,
    destacado: false,
  },
  {
    id: 3,
    nombre: "Lavadora 16 kg Mirage Semiautomática",
    categoria: "Lavadoras",
    imagen: img("lavadoras", "mirage-16-kg"),
    contado: 5199,
    total: 5799,
    enganche: 500,
    financiado: 5299,
    semanas: 18,
    pago: 295,
    destacado: false,
  },
  {
    id: 4,
    nombre: "Lavadora 22 kg Mirage Semiautomática",
    categoria: "Lavadoras",
    imagen: img("lavadoras", "mirage-22-kg"),
    contado: 6499,
    total: 7299,
    enganche: 700,
    financiado: 6599,
    semanas: 18,
    pago: 367,
    destacado: false,
  },
  {
    id: 5,
    nombre: "Lavadora 19 kg LG Automática",
    categoria: "Lavadoras",
    imagen: img("lavadoras", "lg-19-kg"),
    contado: 10499,
    total: 12499,
    enganche: 1000,
    financiado: 11499,
    semanas: 30,
    pago: 384,
    destacado: false,
  },
  {
    id: 6,
    nombre: "Lavadora 20 kg Koblenz Automática",
    categoria: "Lavadoras",
    imagen: img("lavadoras", "koblenz-20-kg"),
    contado: 10799,
    total: 12799,
    enganche: 1000,
    financiado: 11799,
    semanas: 30,
    pago: 394,
    destacado: false,
  },

  // ================= ESTUFAS =================
  {
    id: 7,
    nombre: 'Estufa Acros 30" Manual',
    categoria: "Estufas",
    imagen: img("estufas", "estufa-acros-30-manual"),
    contado: 5999,
    total: 6999,
    enganche: 600,
    financiado: 6399,
    semanas: 22,
    pago: 291,
    destacado: false,
  },
  {
    id: 8,
    nombre: 'Estufa Acros 30" Electrónico',
    categoria: "Estufas",
    imagen: img("estufas", "estufa-acros-30-electronico"),
    contado: 7599,
    total: 8499,
    enganche: 600,
    financiado: 7899,
    semanas: 22,
    pago: 360,
    destacado: false,
  },
  {
    id: 9,
    nombre: 'Estufa Mabe 20" Gris',
    categoria: "Estufas",
    imagen: img("estufas", "estufa-mabe-20-gris"),
    contado: 5099,
    total: 6199,
    enganche: 500,
    financiado: 5699,
    semanas: 20,
    pago: 285,
    destacado: false,
  },
  {
    id: 10,
    nombre: 'Estufa Midea 20" Negra/Gris',
    categoria: "Estufas",
    imagen: img("estufas", "estufa-midea-20-negra-gris"),
    contado: 5399,
    total: 6099,
    enganche: 450,
    financiado: 5649,
    semanas: 20,
    pago: 283,
    destacado: false,
  },
  {
    id: 11,
    nombre: 'Estufa Garell 20" con Gabinete',
    categoria: "Estufas",
    imagen: img("estufas", "estufa-de-gabinete-garell-20"),
    contado: 3300,
    total: 3999,
    enganche: 400,
    financiado: 3599,
    semanas: 18,
    pago: 200,
    destacado: false,
  },

  // ================= PARRILLAS =================
  {
    id: 12,
    nombre: "Parrilla de Mesa 4Q",
    categoria: "Parrillas",
    imagen: img("parrillas", "parrilla-de-mesa"),
    contado: 899,
    total: 1099,
    enganche: 200,
    financiado: 899,
    semanas: 9,
    pago: 100,
    destacado: false,
  },
  {
    id: 13,
    nombre: "Parrilla Empotrable 4Q Cristal",
    categoria: "Parrillas",
    imagen: img(
      "parrillas",
      "parrilla-empotrable-cristal-templado-4-quemadores",
    ),
    contado: 2899,
    total: 3349,
    enganche: 300,
    financiado: 3049,
    semanas: 16,
    pago: 191,
    destacado: false,
  },
  {
    id: 14,
    nombre: "Parrilla Empotrable 4Q Acero",
    categoria: "Parrillas",
    imagen: img(
      "parrillas",
      "parrilla-empotrable-acero-inoxidable-4-quemadores",
    ),
    contado: 2599,
    total: 2999,
    enganche: 275,
    financiado: 2724,
    semanas: 16,
    pago: 171,
    destacado: false,
  },
  {
    id: 15,
    nombre: "Parrilla Empotrable 5Q Cristal",
    categoria: "Parrillas",
    imagen: img("parrillas", "parrilla-5-quemadores-cristal-templado"),
    contado: 3099,
    total: 3699,
    enganche: 400,
    financiado: 3299,
    semanas: 16,
    pago: 207,
    destacado: false,
  },
  {
    id: 16,
    nombre: "Parrilla Empotrable 5Q Acero",
    categoria: "Parrillas",
    imagen: img("parrillas", "parrilla-5-quemadores-acero-inoxidable"),
    contado: 3099,
    total: 3499,
    enganche: 400,
    financiado: 3099,
    semanas: 16,
    pago: 194,
    destacado: false,
  },

  // ================= CILINDROS =================
  {
    id: 17,
    nombre: "Cilindro de Gas 9 kg",
    categoria: "Cilindros",
    imagen: img("cilindros", "cilindro-de-gas-9-kg"),
    contado: 1650,
    total: 1999,
    enganche: 200,
    financiado: 1799,
    semanas: 12,
    pago: 150,
    destacado: false,
  },
  {
    id: 18,
    nombre: "Cilindro de Gas 20 kg",
    categoria: "Cilindros",
    imagen: img("cilindros", "cilindro-de-gas-20-kg"),
    contado: 2399,
    total: 2949,
    enganche: 300,
    financiado: 2649,
    semanas: 14,
    pago: 190,
    destacado: false,
  },

  // ================= PANTALLAS =================
  {
    id: 19,
    nombre: 'LG 55"',
    categoria: "Pantallas",
    imagen: img("pantalla", "lg-55-pulgadas"),
    contado: 9699,
    total: 10899,
    enganche: 800,
    financiado: 10099,
    semanas: 24,
    pago: 421,
    destacado: false,
  },
  {
    id: 20,
    nombre: 'LG 50"',
    categoria: "Pantallas",
    imagen: img("pantalla", "lg-50-pulgadas"),
    contado: 9399,
    total: 10299,
    enganche: 750,
    financiado: 9549,
    semanas: 24,
    pago: 398,
    destacado: false,
  },
  {
    id: 21,
    nombre: 'Hisense 65"',
    categoria: "Pantallas",
    imagen: img("pantalla", "hisense-65-pulgadas"),
    contado: 11199,
    total: 12299,
    enganche: 800,
    financiado: 11499,
    semanas: 24,
    pago: 480,
    destacado: false,
  },
  {
    id: 22,
    nombre: 'Hisense 55"',
    categoria: "Pantallas",
    imagen: img("pantalla", "hisense-55-pulgadas"),
    contado: 8599,
    total: 9499,
    enganche: 650,
    financiado: 8849,
    semanas: 24,
    pago: 369,
    destacado: false,
  },
  {
    id: 23,
    nombre: 'Hisense 50"',
    categoria: "Pantallas",
    imagen: img("pantalla", "hisense-50-pulgadas"),
    contado: 7899,
    total: 8899,
    enganche: 650,
    financiado: 8249,
    semanas: 24,
    pago: 344,
    destacado: false,
  },
  {
    id: 24,
    nombre: 'Hisense 43"',
    categoria: "Pantallas",
    imagen: img("pantalla", "hisense-43-pulgadas"),
    contado: 6899,
    total: 7599,
    enganche: 650,
    financiado: 6949,
    semanas: 24,
    pago: 290,
    destacado: false,
  },
  {
    id: 25,
    nombre: 'TCL 50"',
    categoria: "Pantallas",
    imagen: img("pantalla", "tcl-50-pulgadas"),
    contado: 7599,
    total: 8199,
    enganche: 650,
    financiado: 7549,
    semanas: 24,
    pago: 315,
    destacado: false,
  },
  {
    id: 26,
    nombre: 'TCL 43"',
    categoria: "Pantallas",
    imagen: img("pantalla", "tcl-43-pulgadas"),
    contado: 6299,
    total: 7099,
    enganche: 500,
    financiado: 6599,
    semanas: 24,
    pago: 275,
    destacado: false,
  },
  {
    id: 27,
    nombre: 'TCL 40"',
    categoria: "Pantallas",
    imagen: img("pantalla", "tcl-40-pulgadas"),
    contado: 4999,
    total: 5799,
    enganche: 400,
    financiado: 5399,
    semanas: 24,
    pago: 225,
    destacado: false,
  },
  {
    id: 28,
    nombre: 'TCL 32"',
    categoria: "Pantallas",
    imagen: img("pantalla", "tcl-32-pulgadas"),
    contado: 3899,
    total: 4699,
    enganche: 350,
    financiado: 4349,
    semanas: 22,
    pago: 198,
    destacado: false,
  },
  {
    id: 29,
    nombre: 'ONN 65"',
    categoria: "Pantallas",
    imagen: img("pantalla", "onn-65-pulgadas"),
    contado: 9999,
    total: 10799,
    enganche: 800,
    financiado: 9999,
    semanas: 24,
    pago: 417,
    destacado: false,
  },
  {
    id: 30,
    nombre: 'ONN 50"',
    categoria: "Pantallas",
    imagen: img("pantalla", "onn-50-pulgadas"),
    contado: 7199,
    total: 7999,
    enganche: 800,
    financiado: 7199,
    semanas: 24,
    pago: 300,
    destacado: false,
  },
  {
    id: 31,
    nombre: 'AIWA 43"',
    categoria: "Pantallas",
    imagen: img("pantalla", "aiwa-43-pulgadas"),
    contado: 5399,
    total: 6199,
    enganche: 400,
    financiado: 5799,
    semanas: 24,
    pago: 242,
    destacado: false,
  },
  {
    /*id: 32,
    nombre: 'AIWA 40"',
    categoria: "Pantallas",
    imagen: img("pantalla", "aiwa-40-pulgadas"),
    contado: 3699,
    total: 5199,
    enganche: 400,
    financiado: 4799,
    semanas: 24,
    pago: 200,
    destacado: false,
  */},
  {
    id: 33,
    nombre: 'AIWA 32"',
    categoria: "Pantallas",
    imagen: img("pantalla", "aiwa-32-pulgadas"),
    contado: 3899,
    total: 4399,
    enganche: 350,
    financiado: 4049,
    semanas: 22,
    pago: 185,
    destacado: false,
  },
  {
    id: 34,
    nombre: 'GHIA 32"',
    categoria: "Pantallas",
    imagen: img("pantalla", "ghia-32-pulgadas"),
    contado: 3299,
    total: 3949,
    enganche: 250,
    financiado: 3699,
    semanas: 18,
    pago: 206,
    destacado: false,
  },

  // ================= VENTILADORES ============
  {
    id: 35,
    nombre: "VENTILADOR MAN",
    categoria: "Ventiladores",
    imagen: img("ventiladores", "ventilador-man"),
    contado: 1399,
    total: 1599,
    enganche: 200,
    financiado: 1599,
    semanas: 10,
    pago: 140,
    destacado: false,
  },
  {
    id: 36,
    nombre: "XBOX SERIE S 512 GB BLANCO",
    categoria: "Consolas",
    imagen: img("consolas", "xbox-serie-s-512-gb"),
    contado: 9049,
    total: 9999,
    enganche: 750,
    financiado: 9249,
    semanas: 24,
    pago: 386,
    destacado: false,
  },
  {
    id: 37,
    nombre: "XBOX SERIE S 1TB BLANCO",
    categoria: "Consolas",
    imagen: img("consolas", "xbox-serie-s-1-tb"),
    contado: 10599,
    total: 11300,
    enganche: 750,
    financiado: 10550,
    semanas: 24,
    pago: 440,
    destacado: false,
  },
  {
    id: 38,
    nombre: "XBOX SERIE X 1TB BLANCO",
    categoria: "Consolas",
    imagen: img("consolas", "xbox-serie-x-1-tb"),
    contado: 13699,
    total: 14899,
    enganche: 1500,
    financiado: 13399,
    semanas: 28,
    pago: 479,
    destacado: false,
  },
  {
    id: 39,
    nombre: "PLAYSTATION 5 1TB",
    categoria: "Consolas",
    imagen: img("consolas", "playstation-5-1tb"),
    contado: 10349,
    total: 11199,
    enganche: 800,
    financiado: 10399,
    semanas: 24,
    pago: 434,
    destacado: false,
  },
  {
    id: 40,
    nombre: "NINTENDO SWITCH OLED",
    categoria: "Consolas",
    imagen: img("consolas", "nintendo-switch-oled"),
    contado: 7499,
    total: 7999,
    enganche: 750,
    financiado: 7249,
    semanas: 22,
    pago: 330,
    destacado: false,
  },
  {
    id: 41,
    nombre: "FRIGOBAR MIRAGE",
    categoria: "Refrigeradores",
    imagen: img("refrigeradores", "frigobar-mirage"),
    contado: 4599,
    total: 5149,
    enganche: 500,
    financiado: 4649,
    semanas: 18,
    pago: 259,
    destacado: false,
  },
  {
    id: 42,
    nombre: "FRIGOBAR HISENSE",
    categoria: "Refrigeradores",
    imagen: img("refrigeradores", "frigobar-hisense"),
    contado: 4599,
    total: 4799,
    enganche: 500,
    financiado: 4299,
    semanas: 18,
    pago: 239,
    destacado: false,
  },
  {
    id: 43,
    nombre: "REFRIGERADOR TCL 7 PIES",
    categoria: "Refrigeradores",
    imagen: img("refrigeradores", "refrigerador-tcl-7-pies"),
    contado: 6599,
    total: 7599,
    enganche: 650,
    financiado: 6949,
    semanas: 24,
    pago: 290,
    destacado: false,
  },
  {
    id: 44,
    nombre: "REFRIGERADOR MABE 10 PIES SIN DISP.",
    categoria: "Refrigeradores",
    imagen: img("refrigeradores",  "mabe-10-pies-sin-dispensador"),
    contado: 9849,
    total: 10599,
    enganche: 1000,
    financiado: 9599,
    semanas: 28,
    pago: 343,
    destacado: false,
  },
  {
    id: 45,
    nombre: "REFRIGERADOR MABE 11 PIES SIN DISP.",
    categoria: "Refrigeradores",
    imagen: img("refrigeradores", "mabe-11-pies-sin-dispensador"),
    contado: 9699,
    total: 10699,
    enganche: 1000,
    financiado: 9699,
    semanas: 28,
    pago: 347,
    destacado: false,
  },
  {
    id: 46,
    nombre: "REFRIGERADOR SAMSUNG 11 PIES",
    categoria: "Refrigeradores",
    imagen: img("refrigeradores", "samsung-11-pies"),
    contado: 9999,
    total: 10999,
    enganche: 1000,
    financiado: 9999,
    semanas: 28,
    pago: 358,
    destacado: false,
  },
  {
    id: 47,
    nombre: "REFRIGERADOR LG 11 PIES",
    categoria: "Refrigeradores",
    imagen: img("refrigeradores", "lg-11-pies"),
    contado: 10899,
    total: 11899,
    enganche: 1000,
    financiado: 10899,
    semanas: 28,
    pago: 390,
    destacado: false,
  },
  {
    id: 48,
    nombre: "REFRIGERADOR SAMSUNG 14 PIES",
    categoria: "Refrigeradores",
    imagen: img("refrigeradores", "samsung-14-pies"),
    contado: 11299,
    total: 12399,
    enganche: 1000,
    financiado: 11399,
    semanas: 28,
    pago: 408,
    destacado: false,
  },
  {
    id: 49,
    nombre: "REFRIGERADOR MABE 14 PIES",
    categoria: "Refrigeradores",
    imagen: img("refrigeradores", "mabe-14-pies"),
    contado: 12299,
    total: 13699,
    enganche: 1250,
    financiado: 12449,
    semanas: 30,
    pago: 415,
    destacado: false,
  },

  // ================= PRODUCTOS NUEVOS 9-8-2026 =================
  {
    id: 50,
    nombre: "COMEDOR 4 PUESTOS",
    categoria: "Comedores",
    imagen: img("comedores", "comedor-4-puestos"),
    contado: 5500,
    total: 5999,
    enganche: 600,
    financiado: 5999,
    semanas: 18,
    pago: 300,
    destacado: false,
  },
  {
    id: 51,
    nombre: "COMEDOR 4 PUESTOS NEGRO",
    categoria: "Comedores",
    imagen: img("comedores", "comedor-4-puestos-negro"),
    contado: 4999,
    total: 5599,
    enganche: 400,
    financiado: 5599,
    semanas: 20,
    pago: 260,
    destacado: false,
  },
  {
    id: 52,
    nombre: "COMEDOR 6 PUESTOS",
    categoria: "Comedores",
    imagen: img("comedores", "comedor-6-puestos"),
    contado: 6999,
    total: 7699,
    enganche: 700,
    financiado: 7699,
    semanas: 20,
    pago: 350,
    destacado: false,
  },
  {
    id: 53,
    nombre: 'VENTILADOR TAURUS DE PISO 20"',
    categoria: "Ventiladores",
    imagen: img("ventiladores", "ventilador-taurus-de-piso-20"),
    contado: 1100,
    total: 1299,
    enganche: 200,
    financiado: 1299,
    semanas: 10,
    pago: 110,
    destacado: false,
  },
  {
    id: 54,
    nombre: 'VENTILADOR TAURUS DE PEDESTAL 16"',
    categoria: "Ventiladores",
    imagen: img("ventiladores", "ventilador-taurus-de-pedestal-16"),
    contado: 970,
    total: 1099,
    enganche: 150,
    financiado: 1099,
    semanas: 8,
    pago: 120,
    destacado: false,
  },
  {
    id: 55,
    nombre: 'VENTILADOR TAURUS ECOJET DE PEDESTAL 18"',
    categoria: "Ventiladores",
    imagen: img("ventiladores", "ventilador-taurus-ecojet-de-pedestal-18"),
    contado: 1250,
    total: 1250,
    enganche: 250,
    financiado: 1250,
    semanas: 8,
    pago: 125,
    destacado: false,
  },
  {
    id: 56,
    nombre: "HORNO DE MICROONDAS MIRAGE 0.7",
    categoria: "Microondas",
    imagen: img("microondas", "horno-de-microondas-mirage-07"),
    contado: 1999,
    total: 2499,
    enganche: 250,
    financiado: 2499,
    semanas: 12,
    pago: 188,
    destacado: false,
  },
  {
    id: 57,
    nombre: "HORNO DE MICROONDAS MIRAGE 1.1",
    categoria: "Microondas",
    imagen: img("microondas", "horno-de-microondas-mirage-11"),
    contado: 2699,
    total: 2999,
    enganche: 300,
    financiado: 2999,
    semanas: 12,
    pago: 225,
    destacado: false,
  },
  {
    id: 58,
    nombre: "HORNO DE MICROONDAS MABE ESPEJO 1.1",
    categoria: "Microondas",
    imagen: img("microondas", "horno-de-microondas-mabe-espejo-11"),
    contado: 3199,
    total: 3599,
    enganche: 350,
    financiado: 3599,
    semanas: 14,
    pago: 233,
    destacado: false,
  },
  {
    id: 59,
    nombre: "LICUADORA NINJA",
    categoria: "Licuadoras",
    imagen: img("licuadoras", "licuadora-ninja"),
    contado: 2499,
    total: 2860,
    enganche: 300,
    financiado: 2860,
    semanas: 16,
    pago: 160,
    destacado: false,
  },
  {
    id: 60,
    nombre: "LICUADORA BLACK & DECKER",
    categoria: "Licuadoras",
    imagen: img("licuadoras", "licuadora-black-decker"),
    contado: 1499,
    total: 1899,
    enganche: 250,
    financiado: 1899,
    semanas: 11,
    pago: 150,
    destacado: false,
  },
  {
    id: 61,
    nombre: "LICUADORA DIGITAL OSTER",
    categoria: "Licuadoras",
    imagen: img("licuadoras", "licuadora-digital-oster"),
    contado: 1799,
    total: 2249,
    enganche: 250,
    financiado: 2249,
    semanas: 13,
    pago: 154,
    destacado: false,
  },
  {
    id: 62,
    nombre: 'AIWA 40"',
    categoria: "Pantallas",
    imagen: img("pantalla", "aiwa-40-pulgadas"),
    contado: 4999,
    total: 5799,
    enganche: 400,
    financiado: 5799,
    semanas: 24,
    pago: 225,
    destacado: false,
  },
  {
    id: 63,
    nombre: "VANITY DE 6 GAVETAS BLANCO",
    categoria: "Vanidades",
    imagen: img("vanidades", "vanity-6-gavetas-blanco"),
    contado: 4899,
    total: 5499,
    enganche: 500,
    financiado: 5499,
    semanas: 18,
    pago: 278,
    destacado: true,
  },
  {
    id: 64,
    nombre: "VANITY DE 6 GAVETAS GRIS",
    categoria: "Vanidades",
    imagen: img("vanidades", "vanity-6-gavetas-gris"),
    contado: 4899,
    total: 5499,
    enganche: 500,
    financiado: 5499,
    semanas: 18,
    pago: 278,
    destacado: true,
  },
  {
    id: 65,
    nombre: "COLCHÓN MATRIMONIAL MARCA AMERICA",
    categoria: "Colchones",
    imagen: img("colchones", "colchon-matrimonial-marca-america"),
    contado: 4299,
    total: 4999,
    enganche: 500,
    financiado: 4999,
    semanas: 16,
    pago: 282,
    destacado: true,
  },
  {
    id: 66,
    nombre: "COLCHÓN MATRIMONIAL AURA PLUS LESTER",
    categoria: "Colchones",
    imagen: img("colchones", "colchon-matrimonial-aura-plus-lester"),
    contado: 3150,
    total: 3500,
    enganche: 300,
    financiado: 3500,
    semanas: 16,
    pago: 200,
    destacado: true,
  },
  {
    id: 67,
    nombre: "LAVADORA ACROS 15 KG",
    categoria: "Lavadoras",
    imagen: img("lavadoras", "lavadora-acros-15-kg"),
    contado: 3699,
    total: 4299,
    enganche: 350,
    financiado: 4299,
    semanas: 16,
    pago: 247,
    destacado: true,
  },
  {
    id: 68,
    nombre: "LAVADORA ACROS 22 KG",
    categoria: "Lavadoras",
    imagen: img("lavadoras", "lavadora-acros-22-kg"),
    contado: 4350,
    total: 4999,
    enganche: 450,
    financiado: 4999,
    semanas: 16,
    pago: 285,
    destacado: true,
  },
  {
    id: 69,
    nombre: 'ESTUFA ACROS 20" NEGRA',
    categoria: "Estufas",
    imagen: img("estufas", "estufa-acros-20-negra"),
    contado: 4899,
    total: 5599,
    enganche: 500,
    financiado: 5599,
    semanas: 18,
    pago: 284,
    destacado: true,
  },
  {
    id: 70,
    nombre: 'ESTUFA ACROS 20" ACERO INOXIDABLE',
    categoria: "Estufas",
    imagen: img("estufas", "estufa-acros-20-acero-inoxidable"),
    contado: 5200,
    total: 5999,
    enganche: 550,
    financiado: 5999,
    semanas: 18,
    pago: 303,
    destacado: true,
  },
];

// Función para obtener productos destacados
function obtenerProductosDestacados() {
  return productos.filter((p) => p.destacado);
}

// Función para obtener productos por categoría
function obtenerProductosPorCategoria(categoria) {
  if (categoria === "Todos") {
    return productos;
  }
  return productos.filter((p) => p.categoria === categoria);
}

// Función para obtener todas las categorías
function obtenerCategorias() {
  const categorias = [...new Set(productos.map((p) => p.categoria))];
  return ["Todos", ...categorias];
}

// Función para crear una tarjeta de producto HTML
function crearTarjetaProducto(producto) {
  const descuento = producto.total && producto.contado ? Math.round(
    ((producto.total - producto.contado) / producto.total) * 100,
  ) : 0;

  const contadoFormatted = producto.contado ? producto.contado.toLocaleString() : 'N/A';
  const totalFormatted = producto.total ? producto.total.toLocaleString() : 'N/A';

  return `
        <div class="product-card">
            <div class="product-image-container">
                <img src="${producto.imagen}" alt="${producto.nombre}" class="product-img">
                ${DESCUENTOS_ACTIVOS && descuento > 0 ? `<span class="discount-badge">-${descuento}%</span>` : ""}
            </div>
            <div class="product-info">
                <h3 class="product-title" data-id="${producto.id}">${producto.nombre}</h3>
                <p class="product-category">${producto.categoria}</p>
                <div class="product-price">
                    <span class="current-price">De contado por: $${contadoFormatted}</span>
                    
                </div>
                <div class="product-financing">
                    <small>O Financiado por: $${totalFormatted}</small>
                </div>
            </div>
        </div>
    `;
}


// Delegación: abrir galería cuando se hace click en cualquier tarjeta de producto
// Si la función abrirGaleriaProducto está disponible (se define en catalogo.js), se utilizara.
// En caso contrario redirigimos al catálogo para que el usuario pueda ver el modal.
document.addEventListener("click", function (e) {
  const card = e.target.closest && e.target.closest(".product-card");
  if (!card) return;

  const id = card.querySelector(".product-title")?.dataset?.id;
  let productoObj = null;

  if (id) {
    productoObj = productos.find((p) => String(p.id) === String(id));
  }

  if (!productoObj) {
    const img = card.querySelector(".product-img");
    if (img) {
      productoObj = productos.find((p) => {
        try {
          return img.src && img.src.indexOf(p.imagen) !== -1;
        } catch {
          return false;
        }
      });
    }
  }

  if (productoObj) {
    if (typeof abrirGaleriaProducto === "function") {
      abrirGaleriaProducto(productoObj);
      // evitar que otro listener haga lo mismo de nuevo
      e.stopPropagation();
    } else {
      // si estamos en otra página (p.ej. index), llevar al catálogo y pasar id
      window.location.href = `catalogo.html?prod=${encodeURIComponent(productoObj.id)}`;
    }
  }
});
